from mrp.views.test import *
from mrp.views.shiftview import *
from mrp.views.zayeatvaznview import *
from mrp.views.asset_failure_view import *
from mrp.views.asset_randeman_view import *
from mrp.views.dashboardview import *
from mrp.views.assetRandemanInitview import *
from mrp.views.profileview import *
from mrp.views.reportview import *
from mrp.views.moshakhasview import *
