# Generated by Django 3.2.6 on 2025-10-15 10:51

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='نام واحد')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='کد واحد')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_departments', to=settings.AUTH_USER_MODEL, verbose_name='مدیر واحد')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_departments', to='automation.department', verbose_name='واحد والد')),
            ],
            options={
                'verbose_name': 'واحد سازمانی',
                'verbose_name_plural': 'واحدهای سازمانی',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_code', models.CharField(max_length=50, unique=True, verbose_name='کد پرسنلی')),
                ('position', models.CharField(choices=[('staff', 'کارمند'), ('expert', 'کارشناس'), ('senior_expert', 'کارشناس ارشد'), ('supervisor', 'سرپرست'), ('manager', 'مدیر'), ('director', 'مدیر کل')], default='staff', max_length=20, verbose_name='سمت')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='تلفن داخلی')),
                ('mobile', models.CharField(blank=True, max_length=15, verbose_name='موبایل')),
                ('signature', models.ImageField(blank=True, null=True, upload_to='signatures/', verbose_name='امضا')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('joined_date', models.DateField(blank=True, null=True, verbose_name='تاریخ استخدام')),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='automation.department', verbose_name='واحد')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'کارمند',
                'verbose_name_plural': 'کارمندان',
                'ordering': ['user__last_name', 'user__first_name'],
            },
        ),
        migrations.CreateModel(
            name='Mail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mail_number', models.CharField(max_length=100, unique=True, verbose_name='شماره نامه')),
                ('title', models.CharField(max_length=500, verbose_name='عنوان')),
                ('content', models.TextField(verbose_name='متن نامه')),
                ('status', models.CharField(choices=[('new', 'جدید'), ('pending', 'در انتظار'), ('in_progress', 'در حال بررسی'), ('signed', 'امضا شده'), ('completed', 'تکمیل شده'), ('archived', 'بایگانی شده'), ('rejected', 'رد شده')], default='new', max_length=20, verbose_name='وضعیت')),
                ('priority', models.CharField(choices=[('normal', 'عادی'), ('urgent', 'فوری'), ('very_urgent', 'بسیار فوری')], default='normal', max_length=20, verbose_name='اولویت')),
                ('is_internal', models.BooleanField(default=True, verbose_name='داخلی')),
                ('is_confidential', models.BooleanField(default=False, verbose_name='محرمانه')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ ارسال')),
                ('deadline', models.DateTimeField(blank=True, null=True, verbose_name='مهلت پاسخ')),
                ('receiver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_mails', to='automation.employee', verbose_name='گیرنده')),
                ('receiver_department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_mails', to='automation.department', verbose_name='واحد گیرنده')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_mails', to='automation.employee', verbose_name='فرستنده')),
                ('sender_department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_mails', to='automation.department', verbose_name='واحد فرستنده')),
            ],
            options={
                'verbose_name': 'نامه',
                'verbose_name_plural': 'نامه\u200cها',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MailAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='mail_attachments/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'txt', 'jpg', 'png', 'xlsx', 'xls'])], verbose_name='فایل')),
                ('original_filename', models.CharField(max_length=255, verbose_name='نام فایل')),
                ('file_size', models.IntegerField(verbose_name='حجم فایل (بایت)')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ آپلود')),
                ('description', models.CharField(blank=True, max_length=500, verbose_name='توضیحات')),
                ('mail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='automation.mail', verbose_name='نامه')),
            ],
            options={
                'verbose_name': 'پیوست',
                'verbose_name_plural': 'پیوست\u200cها',
                'ordering': ['uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='SignedDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signed_file', models.FileField(upload_to='signed_documents/%Y/%m/', verbose_name='فایل امضا شده')),
                ('file_hash', models.CharField(blank=True, help_text='SHA256 hash برای تایید یکپارچگی', max_length=64, verbose_name='هش فایل')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('mail', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='signed_document', to='automation.mail', verbose_name='نامه')),
                ('original_attachment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signed_versions', to='automation.mailattachment', verbose_name='فایل اصلی')),
            ],
            options={
                'verbose_name': 'سند امضا شده',
                'verbose_name_plural': 'اسناد امضا شده',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('new_mail', 'نامه جدید'), ('referral', 'ارجاع'), ('signature_request', 'درخواست امضا'), ('deadline_reminder', 'یادآوری مهلت'), ('status_change', 'تغییر وضعیت')], max_length=30, verbose_name='نوع اعلان')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('message', models.TextField(verbose_name='پیام')),
                ('is_read', models.BooleanField(default=False, verbose_name='خوانده شده')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ خواندن')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('mail', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='automation.mail', verbose_name='نامه مرتبط')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='automation.employee', verbose_name='گیرنده')),
            ],
            options={
                'verbose_name': 'اعلان',
                'verbose_name_plural': 'اعلان\u200cها',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان قالب')),
                ('content', models.TextField(verbose_name='متن قالب')),
                ('is_public', models.BooleanField(default=False, verbose_name='عمومی')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='automation.employee', verbose_name='ایجاد کننده')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='automation.department', verbose_name='واحد')),
            ],
            options={
                'verbose_name': 'قالب نامه',
                'verbose_name_plural': 'قالب\u200cهای نامه',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='MailSignature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approval_type', models.CharField(choices=[('approved', 'تایید'), ('conditional_approval', 'تایید با شرط'), ('rejected', 'رد'), ('need_review', 'نیاز به بررسی بیشتر'), ('seen', 'مشاهده شده')], max_length=30, verbose_name='نوع تایید')),
                ('signature_image', models.ImageField(upload_to='signatures/digital/%Y/%m/', verbose_name='تصویر امضا')),
                ('note', models.TextField(blank=True, verbose_name='نظرات و توضیحات')),
                ('position', models.CharField(choices=[('header', 'سربرگ'), ('footer', 'پاورقی'), ('end', 'انتهای سند'), ('custom', 'موقعیت دلخواه')], default='end', max_length=20, verbose_name='موقعیت امضا')),
                ('signed_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ امضا')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='آدرس IP')),
                ('mail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signatures', to='automation.mail', verbose_name='نامه')),
                ('signer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signatures', to='automation.employee', verbose_name='امضا کننده')),
            ],
            options={
                'verbose_name': 'امضا',
                'verbose_name_plural': 'امضاها',
                'ordering': ['signed_at'],
            },
        ),
        migrations.CreateModel(
            name='MailReferral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referral_type', models.CharField(choices=[('info', 'اطلاع'), ('action', 'اقدام'), ('review', 'بررسی و نظر'), ('follow_up', 'پیگیری'), ('approval', 'تایید')], max_length=20, verbose_name='نوع ارجاع')),
                ('status', models.CharField(choices=[('pending', 'در انتظار'), ('seen', 'مشاهده شده'), ('in_progress', 'در حال اقدام'), ('completed', 'اقدام شده'), ('returned', 'برگشت داده شده')], default='pending', max_length=20, verbose_name='وضعیت')),
                ('note', models.TextField(blank=True, verbose_name='توضیحات ارجاع')),
                ('response', models.TextField(blank=True, verbose_name='پاسخ')),
                ('is_urgent', models.BooleanField(default=False, verbose_name='فوری')),
                ('deadline', models.DateTimeField(blank=True, null=True, verbose_name='مهلت')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ارجاع')),
                ('seen_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ مشاهده')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ اقدام')),
                ('mail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referrals', to='automation.mail', verbose_name='نامه')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referrals_received', to='automation.employee', verbose_name='گیرنده ارجاع')),
                ('recipient_department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='automation.department', verbose_name='واحد گیرنده')),
                ('referrer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referrals_made', to='automation.employee', verbose_name='ارجاع دهنده')),
            ],
            options={
                'verbose_name': 'ارجاع',
                'verbose_name_plural': 'ارجاعات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MailHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('created', 'ایجاد شد'), ('sent', 'ارسال شد'), ('received', 'دریافت شد'), ('referred', 'ارجاع داده شد'), ('signed', 'امضا شد'), ('status_changed', 'وضعیت تغییر کرد'), ('edited', 'ویرایش شد'), ('archived', 'بایگانی شد'), ('comment_added', 'نظر افزوده شد')], max_length=30, verbose_name='عملیات')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('old_value', models.TextField(blank=True, verbose_name='مقدار قبلی')),
                ('new_value', models.TextField(blank=True, verbose_name='مقدار جدید')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='آدرس IP')),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='automation.employee', verbose_name='کاربر')),
                ('mail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='automation.mail', verbose_name='نامه')),
            ],
            options={
                'verbose_name': 'تاریخچه',
                'verbose_name_plural': 'تاریخچه\u200cها',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['recipient', 'is_read', '-created_at'], name='automation__recipie_6f917e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='mailsignature',
            unique_together={('mail', 'signer')},
        ),
        migrations.AddIndex(
            model_name='mailreferral',
            index=models.Index(fields=['status'], name='automation__status_437199_idx'),
        ),
        migrations.AddIndex(
            model_name='mailreferral',
            index=models.Index(fields=['recipient', '-created_at'], name='automation__recipie_9fdfa9_idx'),
        ),
        migrations.AddIndex(
            model_name='mailhistory',
            index=models.Index(fields=['mail', '-created_at'], name='automation__mail_id_2fce4d_idx'),
        ),
        migrations.AddIndex(
            model_name='mail',
            index=models.Index(fields=['mail_number'], name='automation__mail_nu_efe059_idx'),
        ),
        migrations.AddIndex(
            model_name='mail',
            index=models.Index(fields=['status'], name='automation__status_1147ad_idx'),
        ),
        migrations.AddIndex(
            model_name='mail',
            index=models.Index(fields=['-created_at'], name='automation__created_34a4ec_idx'),
        ),
    ]
