# Generated by Django 3.2.6 on 2023-12-02 08:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mrp', '0002_asset_machinecategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Formula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('formula', models.CharField(max_length=255)),
                ('machine', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mrp.asset')),
            ],
            options={
                'db_table': 'formula',
            },
        ),
        migrations.CreateModel(
            name='DailyProduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dayOfIssue', models.DateField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('register_user', models.CharField(max_length=100)),
                ('nomre', models.FloatField()),
                ('counter', models.IntegerField()),
                ('production_value', models.IntegerField(blank=True, null=True)),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mrp.asset')),
            ],
            options={
                'db_table': 'dailyproduction',
            },
        ),
    ]
