# Generated by Django 3.2.6 on 2025-08-18 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mrp', '0002_auto_20250818_1809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyproduction',
            name='operators_data',
            field=models.TextField(blank=True, null=True),
        ),
    ]
