# Generated by Django 3.2.6 on 2025-08-18 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mrp', '0003_alter_dailyproduction_operators_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyproduction',
            name='operators_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
