# Generated by Django 3.2.6 on 2023-12-02 17:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mrp', '0004_dailyproduction_speed'),
    ]

    operations = [
        migrations.CreateModel(
            name='SysUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=20)),
                ('token', models.CharField(blank=True, max_length=20, null=True)),
                ('fullName', models.CharField(max_length=50, verbose_name='مشخصات کامل')),
                ('personalCode', models.CharField(max_length=50, verbose_name='کد پرسنلی')),
                ('title', models.CharField(blank=True, max_length=50, null=True, verbose_name='عنوان')),
                ('email', models.EmailField(blank=True, max_length=70, null=True, unique=True, verbose_name='ایمیل')),
                ('tel1', models.CharField(blank=True, max_length=50, null=True, verbose_name='تلفن')),
                ('tel2', models.CharField(blank=True, max_length=50, null=True, verbose_name='تلفن 2')),
                ('addr1', models.CharField(blank=True, max_length=50, null=True, verbose_name='آدرس')),
                ('addr2', models.CharField(blank=True, max_length=50, null=True, verbose_name='آدرس 2')),
                ('city', models.CharField(blank=True, max_length=50, null=True, verbose_name='شهر')),
                ('state', models.CharField(blank=True, max_length=50, null=True, verbose_name='استان')),
                ('country', models.CharField(blank=True, max_length=50, null=True, verbose_name='کشور')),
                ('postalCode', models.CharField(blank=True, max_length=50, null=True, verbose_name='کدپستی')),
                ('hourlyRate', models.FloatField(blank=True, default=0, null=True, verbose_name='نرخ دستمزد ساعتی')),
                ('defaultLoginLocation', models.FloatField(blank=True, choices=[(1, 'داشبورد'), (2, 'درخواستهای انتسابی به من'), (3, 'صندوق ورودی پیامها'), (4, 'درخواست')], null=True, verbose_name='صفحه پیش فرض')),
                ('profileImage', models.ImageField(blank=True, default=None, upload_to='images/')),
                ('userStatus', models.BooleanField(default=True, verbose_name='وضعیت')),
                ('userId', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'sysusers',
                'ordering': ['title'],
            },
        ),
    ]
