# Generated by Django 3.2.6 on 2025-08-18 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mrp', '0004_alter_dailyproduction_operators_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operator',
            name='CardNo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='operator',
            name='CpCode',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='operator',
            name='FName',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='operator',
            name='LName',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='operator',
            name='PNumber',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
