# Generated by Django 3.2.6 on 2025-08-18 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mrp', '0005_auto_20250818_1816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operator',
            name='Pid',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
