# Generated by Django 3.2.6 on 2023-12-02 17:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mrp', '0005_sysuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'shift',
            },
        ),
        migrations.AlterField(
            model_name='dailyproduction',
            name='machine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dailyproduction_machine', to='mrp.asset'),
        ),
        migrations.AddField(
            model_name='dailyproduction',
            name='shift',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='dailyproduction_shift', to='mrp.shift'),
            preserve_default=False,
        ),
    ]
