# Generated by Django 3.2.6 on 2025-08-23 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mrp', '0006_alter_operator_pid'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='color',
            options={'ordering': ['name']},
        ),
        migrations.AlterField(
            model_name='entryform',
            name='color',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mrp.color', verbose_name='رنگ'),
        ),
        migrations.AlterField(
            model_name='entryform',
            name='la',
            field=models.IntegerField(blank=True, null=True, verbose_name='لا'),
        ),
        migrations.AlterField(
            model_name='entryform',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='نام'),
        ),
        migrations.AlterField(
            model_name='entryform',
            name='tool',
            field=models.IntegerField(blank=True, null=True, verbose_name='طول'),
        ),
        migrations.CreateModel(
            name='UserShiftAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('production_line', models.ForeignKey(limit_choices_to={'assetIsLocatedAt': 'null'}, on_delete=django.db.models.deletion.CASCADE, to='mrp.asset', verbose_name='خط تولید')),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mrp.shift', verbose_name='شیفت')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shift_accesses', to='mrp.sysuser', verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'دسترسی کاربر به شیفت',
                'verbose_name_plural': 'دسترسی\u200cهای کاربران به شیفت',
                'unique_together': {('user', 'production_line', 'shift')},
            },
        ),
    ]
