# Generated by Django 3.2.6 on 2023-12-02 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mrp', '0006_auto_20231202_2059'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailyproduction',
            name='shift',
        ),
    ]
