# Generated by Django 3.2.6 on 2023-12-03 03:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mrp', '0008_dailyproduction_shift'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailyproduction',
            name='shift',
        ),
    ]
