# Generated by Django 3.2.6 on 2025-08-24 06:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mrp', '0008_auto_20250823_1846'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetrandemaninit',
            name='production_line',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ranemna_productionn_line', to='mrp.asset'),
        ),
    ]
