# Generated by Django 3.2.6 on 2025-08-24 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mrp', '0009_assetrandemaninit_production_line'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetrandemaninit',
            name='mablaghe_kole_randeman',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='مبلغ کل راندمان (واقعی)'),
        ),
        migrations.AlterField(
            model_name='assetrandemaninit',
            name='mablaghe_kole_randeman_round',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='مبلغ کل راندمان (واقعی)'),
        ),
        migrations.AlterField(
            model_name='assetrandemaninit',
            name='max_randeman',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='حداکثر راندمان'),
        ),
        migrations.AlterField(
            model_name='assetrandemaninit',
            name='operator_count',
            field=models.IntegerField(default=0, verbose_name='تعداد اپراتور'),
        ),
        migrations.AlterField(
            model_name='assetrandemaninit',
            name='randeman_mazrab_3',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='مضرب 3 رانمان'),
        ),
        migrations.AlterField(
            model_name='assetrandemaninit',
            name='randeman_tolid',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='راندمان تولید'),
        ),
        migrations.AlterField(
            model_name='assetrandemaninit',
            name='randeman_yek_dastgah',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='راندمان کل یک دستگاه'),
        ),
    ]
