# Generated by Django 3.2.6 on 2025-08-24 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mrp', '0010_auto_20250824_1032'),
    ]

    operations = [
        migrations.CreateModel(
            name='OperatorProduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tolid', models.FloatField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('assetrandeman', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productions', to='mrp.assetrandemanlist')),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asset_operator_productions', to='mrp.asset')),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operator_productions', to='mrp.operator')),
            ],
            options={
                'verbose_name': 'OperatorProduction',
                'verbose_name_plural': 'OperatorProductions',
            },
        ),
    ]
