# Generated by Django 3.2.6 on 2025-08-24 10:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mrp', '0011_operatorproduction'),
    ]

    operations = [
        migrations.AddField(
            model_name='operatorproduction',
            name='assetrandeman_init',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='operator_productions_init', to='mrp.assetrandemaninit'),
            preserve_default=False,
        ),
    ]
