# Generated by Django 3.2.6 on 2025-08-24 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mrp', '0012_operatorproduction_assetrandeman_init'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operatorproduction',
            name='assetrandeman_init',
        ),
    ]
