# Generated by Django 3.2.6 on 2023-12-03 05:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mrp', '0012_delete_speedformula'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpeedFormula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('formula', models.CharField(max_length=255)),
                ('machine', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mrp.asset')),
            ],
            options={
                'db_table': 'speedformula',
            },
        ),
    ]
