# Generated by Django 3.2.6 on 2025-08-26 05:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mrp', '0013_remove_operatorproduction_assetrandeman_init'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usershiftaccess',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='shift_accesses', to='mrp.sysuser', verbose_name='کاربر'),
        ),
    ]
