# Generated by Django 3.2.6 on 2025-08-26 05:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mrp', '0014_alter_usershiftaccess_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usershiftaccess',
            name='shift',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_shift', to='mrp.shift', verbose_name='شیفت'),
        ),
    ]
