# Generated by Django 3.2.6 on 2025-09-09 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mrp', '0015_alter_usershiftaccess_shift'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyproduction',
            name='enzebat_value',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dailyproduction',
            name='qc_value',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
