# Generated by Django 3.2.6 on 2025-09-10 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mrp', '0016_auto_20250909_1934'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='dailyproduction',
            index=models.Index(fields=['dayOfIssue'], name='dailyproduc_dayOfIs_a9a409_idx'),
        ),
        migrations.AddIndex(
            model_name='dailyproduction',
            index=models.Index(fields=['machine'], name='dailyproduc_machine_596ded_idx'),
        ),
        migrations.AddIndex(
            model_name='dailyproduction',
            index=models.Index(fields=['production_value'], name='dailyproduc_product_87a840_idx'),
        ),
        migrations.AddIndex(
            model_name='dailyproduction',
            index=models.Index(fields=['operators_data'], name='operators_data_gin', opclasses=['jsonb_path_ops']),
        ),
    ]
