# Generated by Django 3.2.6 on 2025-09-17 04:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mrp', '0017_auto_20250910_1253'),
    ]

    operations = [
        migrations.CreateModel(
            name='MakanHamgen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomre', models.FloatField()),
                ('makan', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='makan_makanhamgen', to='mrp.asset')),
            ],
            options={
                'db_table': 'makanhamgen',
            },
        ),
    ]
