# Generated by Django 3.2.6 on 2023-12-18 08:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mrp', '0017_productionstandard'),
    ]

    operations = [
        migrations.CreateModel(
            name='Zayeat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('assets', models.ManyToManyField(to='mrp.Asset')),
            ],
        ),
        migrations.CreateModel(
            name='ZayeatVaz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vazn', models.FloatField()),
                ('zayeat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mrp.zayeat')),
            ],
        ),
    ]
