# Generated by Django 3.2.6 on 2023-12-18 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mrp', '0018_zayeat_zayeatvaz'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='zayeat',
            table='zayeat',
        ),
        migrations.AlterModelTable(
            name='zayeatvaz',
            table='zayeatvazn',
        ),
    ]
