# Generated by Django 3.2.6 on 2025-09-17 05:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mrp', '0018_makanhamgen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='makanhamgen',
            name='makan',
            field=models.ForeignKey(limit_choices_to={'assetIsLocatedAt': None}, on_delete=django.db.models.deletion.DO_NOTHING, related_name='makan_makanhamgen', to='mrp.asset'),
        ),
    ]
