# Generated by Django 3.2.6 on 2025-10-21 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mrp', '0019_alter_makanhamgen_makan'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField(default=0, verbose_name='مقدار')),
                ('event_date', models.DateField(verbose_name='تاریخ رویداد')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان')),
                ('type', models.CharField(choices=[('order', 'سفارش تولید'), ('vacation', 'تعطیلات'), ('offday', 'روز تعطیل'), ('maintenance', 'تعمیر و نگهداری')], default='appointment', max_length=50, verbose_name='نوع رویداد')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'رویداد تقویم',
                'verbose_name_plural': 'رویدادهای تقویم',
                'ordering': ['event_date', 'line'],
            },
        ),
        migrations.CreateModel(
            name='ColorCode',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Full name or company name of the customer', max_length=100)),
                ('email', models.EmailField(blank=True, help_text="Customer's contact email", max_length=254, null=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Line',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('capacity_per_day', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Shade',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='manufacturingorder',
            name='delivery_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاریخ تحویل'),
        ),
        migrations.AddField(
            model_name='manufacturingorder',
            name='first_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='manufacturingorder',
            name='hb_type',
            field=models.CharField(blank=True, choices=[('HS', 'HS'), ('HB', 'HB')], max_length=2, null=True, verbose_name='هایبالک/رگولار'),
        ),
        migrations.AddField(
            model_name='manufacturingorder',
            name='second_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bomcomponent',
            name='product',
            field=models.ForeignKey(limit_choices_to={'product_type__in': ['component', 'raw']}, on_delete=django.db.models.deletion.CASCADE, to='mrp.product', verbose_name='محصول'),
        ),
        migrations.AlterField(
            model_name='manufacturingorder',
            name='bom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mrp.billofmaterials'),
        ),
        migrations.AlterField(
            model_name='manufacturingorder',
            name='product_to_manufacture',
            field=models.ForeignKey(blank=True, limit_choices_to={'product_type': 'finished'}, null=True, on_delete=django.db.models.deletion.CASCADE, to='mrp.product'),
        ),
        migrations.AlterField(
            model_name='manufacturingorder',
            name='scheduled_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='customer',
            constraint=models.UniqueConstraint(fields=('name', 'email'), name='unique_customer_name_email'),
        ),
        migrations.AddField(
            model_name='calendarevent',
            name='line',
            field=models.ForeignKey(help_text='خط تولیدی که این رویداد در آن اجرا می\u200cشود', on_delete=django.db.models.deletion.CASCADE, related_name='calendar_events', to='mrp.line', verbose_name='خط تولید'),
        ),
        migrations.AddField(
            model_name='calendarevent',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='calendar_events', to='mrp.manufacturingorder'),
        ),
        migrations.AddField(
            model_name='manufacturingorder',
            name='color_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='mrp.colorcode', verbose_name='کد رنگ'),
        ),
        migrations.AddField(
            model_name='manufacturingorder',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mrp.customer'),
        ),
        migrations.AddField(
            model_name='manufacturingorder',
            name='grade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='mrp.grade', verbose_name='نمره'),
        ),
        migrations.AddField(
            model_name='manufacturingorder',
            name='line',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orderd_line', to='mrp.line'),
        ),
        migrations.AddField(
            model_name='manufacturingorder',
            name='shade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='mrp.shade', verbose_name='شید/رنگ'),
        ),
        migrations.AddConstraint(
            model_name='calendarevent',
            constraint=models.CheckConstraint(check=models.Q(('quantity__gte', 0)), name='calendar_event_quantity_positive'),
        ),
    ]
