# Generated by Django 3.2.6 on 2023-12-18 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mrp', '0019_auto_20231218_1228'),
    ]

    operations = [
        migrations.AddField(
            model_name='zayeatvaz',
            name='dayOfIssue',
            field=models.DateField(default=None),
            preserve_default=False,
        ),
    ]
