# Generated by Django 3.2.6 on 2023-12-25 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mrp', '0021_zayeatvaz_shift'),
    ]

    operations = [
        migrations.CreateModel(
            name='Failure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'failure',
            },
        ),
        migrations.CreateModel(
            name='AssetFailure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.TimeField()),
                ('asset_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mrp.asset')),
                ('failure_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mrp.failure')),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mrp.shift')),
            ],
        ),
    ]
