# Generated by Django 3.2.6 on 2025-11-25 08:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mrp', '0022_alter_sysuser_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyProductionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', 'ایجاد'), ('update', 'ویرایش'), ('delete', 'حذف')], max_length=10, verbose_name='عملیات')),
                ('changed_by', models.CharField(max_length=100, verbose_name='تغییر دهنده')),
                ('changed_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ تغییر')),
                ('old_data', models.JSONField(blank=True, null=True, verbose_name='داده\u200cهای قبلی')),
                ('new_data', models.JSONField(blank=True, null=True, verbose_name='داده\u200cهای جدید')),
                ('changed_fields', models.JSONField(blank=True, null=True, verbose_name='فیلدهای تغییر کرده')),
                ('daily_production', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='mrp.dailyproduction', verbose_name='تولید روزانه')),
            ],
            options={
                'verbose_name': 'لاگ تولید روزانه',
                'verbose_name_plural': 'لاگ\u200cهای تولید روزانه',
                'ordering': ['-changed_at'],
            },
        ),
    ]
