# Generated by Django 3.2.6 on 2023-12-31 09:48

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mrp', '0022_assetfailure_failure'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetfailure',
            name='dayOfIssue',
            field=models.DateField(default=datetime.datetime(2023, 12, 31, 13, 18, 4, 451160)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='assetfailure',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
