# Generated by Django 3.2.6 on 2025-11-28 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mrp', '0023_dailyproductionlog'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='dailyproduction',
            unique_together=set(),
        ),
    ]
