# Generated by Django 3.2.6 on 2024-01-10 06:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mrp', '0024_auto_20240109_1354'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetRandemanPerMonth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tolid_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('mah', models.IntegerField()),
                ('sal', models.IntegerField()),
                ('asset_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mrp.assetcategory')),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mrp.shift')),
            ],
            options={
                'db_table': 'assetrandemanpermonth',
            },
        ),
    ]
