# Generated by Django 3.2.6 on 2025-12-24 07:29

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mrp', '0026_alter_sysuser_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Machine_3d',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_x', models.FloatField(default=0.0, verbose_name='موقعیت X')),
                ('position_z', models.FloatField(default=0.0, verbose_name='موقعیت Z')),
                ('rotation', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(-6.283185307179586), django.core.validators.MaxValueValidator(6.283185307179586)], verbose_name='چرخش (رادیان)')),
            ],
        ),
        migrations.AlterField(
            model_name='entryform',
            name='la',
            field=models.BooleanField(blank=True, null=True, verbose_name='فعال'),
        ),
        migrations.AddIndex(
            model_name='operator',
            index=models.Index(fields=['PNumber'], name='operator_PNumber_2c670b_idx'),
        ),
        migrations.AddIndex(
            model_name='operator',
            index=models.Index(fields=['FName', 'LName'], name='operator_FName_d9a3b4_idx'),
        ),
        migrations.AddField(
            model_name='machine_3d',
            name='machine',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mrp.asset'),
        ),
    ]
