# Generated by Django 3.2.6 on 2024-01-12 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mrp', '0026_assetrandemanlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyproduction',
            name='daf_num',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dailyproduction',
            name='dook_weight',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dailyproduction',
            name='net_weight',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dailyproduction',
            name='weight1',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dailyproduction',
            name='weight2',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dailyproduction',
            name='weight3',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dailyproduction',
            name='weight4',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dailyproduction',
            name='weight5',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
