# Generated by Django 3.2.6 on 2024-01-17 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mrp', '0027_auto_20240112_1534'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyproduction',
            name='makhraj_metraj_daf',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dailyproduction',
            name='metrajdaf1',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dailyproduction',
            name='metrajdaf2',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dailyproduction',
            name='metrajdaf3',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dailyproduction',
            name='metrajdaf4',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dailyproduction',
            name='metrajdaf5',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dailyproduction',
            name='metrajdaf6',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dailyproduction',
            name='metrajdaf7',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dailyproduction',
            name='metrajdaf8',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='failure',
            name='code',
            field=models.CharField(max_length=50, verbose_name='کد'),
        ),
        migrations.AlterField(
            model_name='failure',
            name='name',
            field=models.CharField(max_length=100, verbose_name='نام'),
        ),
    ]
