# Generated by Django 3.2.6 on 2025-12-24 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mrp', '0027_auto_20251224_1059'),
    ]

    operations = [
        migrations.AddField(
            model_name='entryform',
            name='active',
            field=models.BooleanField(blank=True, null=True, verbose_name='فعال'),
        ),
        migrations.AlterField(
            model_name='entryform',
            name='la',
            field=models.IntegerField(blank=True, null=True, verbose_name='لا'),
        ),
    ]
