# Generated by Django 3.2.6 on 2024-02-01 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mrp', '0031_auto_20240129_1627'),
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'color',
            },
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('area', models.FloatField()),
            ],
            options={
                'db_table': 'size',
            },
        ),
        migrations.CreateModel(
            name='Tarh',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'tarh',
            },
        ),
    ]
