# Generated by Django 3.2.6 on 2024-03-02 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mrp', '0032_alter_dailyproduction_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='assetfailure',
            unique_together={('asset_name', 'shift', 'failure_name', 'dayOfIssue')},
        ),
    ]
