# Generated by Django 3.2.6 on 2024-02-01 17:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mrp', '0032_color_size_tarh'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailySingleRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shomare', models.CharField(max_length=100)),
                ('tarakom', models.IntegerField()),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mrp.asset')),
                ('rang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mrp.color')),
                ('sizes', models.ManyToManyField(to='mrp.Size')),
                ('tarh', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mrp.tarh')),
            ],
        ),
    ]
