# Generated by Django 3.2.6 on 2024-03-21 05:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mrp', '0033_alter_assetfailure_unique_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assetfailure',
            options={'ordering': ('shift', 'asset_name', '-duration')},
        ),
        migrations.AddField(
            model_name='nezafatpadash',
            name='asset_randeman_list',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='mrp.assetrandemanlist'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tolidpadash',
            name='asset_randeman_list',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='mrp.assetrandemanlist'),
            preserve_default=False,
        ),
    ]
