# Generated by Django 3.2.6 on 2024-03-21 06:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mrp', '0035_auto_20240321_0942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tolidpadash',
            name='asset_randeman_list',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mrp.assetrandemanlist'),
        ),
        migrations.AlterField(
            model_name='tolidranking',
            name='shift',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='mrp.shift'),
            preserve_default=False,
        ),
    ]
