# Generated by Django 3.2.6 on 2024-03-21 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mrp', '0036_auto_20240321_0944'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nezafatpadash',
            name='asset_randeman_list',
        ),
        migrations.RemoveField(
            model_name='tolidpadash',
            name='asset_randeman_list',
        ),
    ]
