# Generated by Django 3.2.6 on 2024-03-21 06:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mrp', '0040_remove_tolidpadash_asset_randeman_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='tolidpadash',
            name='asset_randeman_list',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ewew', to='mrp.assetrandemanlist'),
        ),
    ]
