# Generated by Django 3.2.6 on 2024-03-21 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mrp', '0043_auto_20240321_1028'),
    ]

    operations = [
        migrations.AddField(
            model_name='tolidranking',
            name='price_personnel',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tolidranking',
            name='price_sarshift',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
