# Generated by Django 3.2.6 on 2024-03-21 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mrp', '0044_auto_20240321_1031'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nezafatranking',
            name='price_personnel',
        ),
        migrations.RemoveField(
            model_name='nezafatranking',
            name='price_sarshift',
        ),
        migrations.RemoveField(
            model_name='tolidranking',
            name='price_personnel',
        ),
        migrations.RemoveField(
            model_name='tolidranking',
            name='price_sarshift',
        ),
    ]
