# Generated by Django 3.2.6 on 2024-03-21 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mrp', '0045_auto_20240321_1327'),
    ]

    operations = [
        migrations.AddField(
            model_name='nezafatranking',
            name='price_personnel',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nezafatranking',
            name='price_sarshift',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tolidranking',
            name='price_personnel',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tolidranking',
            name='price_sarshift',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=10),
            preserve_default=False,
        ),
    ]
