# Generated by Django 3.2.6 on 2024-03-27 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mrp', '0046_auto_20240321_1328'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nezafatpadash',
            name='asset_randeman_list',
        ),
        migrations.RemoveField(
            model_name='tolidpadash',
            name='asset_randeman_list',
        ),
        migrations.AlterField(
            model_name='assetrandemaninit',
            name='mablaghe_kole_randeman',
            field=models.DecimalField(decimal_places=0, max_digits=10, verbose_name='مبلغ کل راندمان (واقعی)'),
        ),
        migrations.AlterField(
            model_name='assetrandemaninit',
            name='mablaghe_kole_randeman_round',
            field=models.DecimalField(decimal_places=0, max_digits=10, verbose_name='مبلغ کل راندمان (واقعی)'),
        ),
        migrations.AlterField(
            model_name='assetrandemaninit',
            name='max_randeman',
            field=models.DecimalField(decimal_places=0, max_digits=10, verbose_name='حداکثر راندمان'),
        ),
        migrations.AlterField(
            model_name='assetrandemaninit',
            name='operator_count',
            field=models.IntegerField(verbose_name='تعداد اپراتور'),
        ),
        migrations.AlterField(
            model_name='assetrandemaninit',
            name='randeman_mazrab_3',
            field=models.DecimalField(decimal_places=0, max_digits=10, verbose_name='مضرب 3 رانمان'),
        ),
        migrations.AlterField(
            model_name='assetrandemaninit',
            name='randeman_tolid',
            field=models.DecimalField(decimal_places=0, max_digits=10, verbose_name='راندمان تولید'),
        ),
        migrations.AlterField(
            model_name='assetrandemaninit',
            name='randeman_yek_dastgah',
            field=models.DecimalField(decimal_places=0, max_digits=10, verbose_name='راندمان کل یک دستگاه'),
        ),
        migrations.AlterUniqueTogether(
            name='assetrandemanlist',
            unique_together={('mah', 'sal')},
        ),
    ]
