# Generated by Django 3.2.6 on 2024-03-29 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mrp', '0048_auto_20240329_1405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nezafatpadash',
            name='price_personnel',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='nezafatpadash',
            name='price_sarshift',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='tolidpadash',
            name='price_personnel',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='tolidpadash',
            name='price_sarshift',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='tolidranking',
            name='price_personnel',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='tolidranking',
            name='price_sarshift',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
