# Generated by Django 3.2.6 on 2024-03-29 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mrp', '0050_auto_20240329_1406'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='شرح')),
                ('time_created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'financialprofile',
            },
        ),
        migrations.AlterField(
            model_name='nezafatpadash',
            name='description',
            field=models.TextField(verbose_name='َشرح'),
        ),
        migrations.AlterField(
            model_name='nezafatpadash',
            name='price_personnel',
            field=models.DecimalField(decimal_places=0, max_digits=10, verbose_name='پاداش پرسنل'),
        ),
        migrations.AlterField(
            model_name='nezafatpadash',
            name='price_sarshift',
            field=models.DecimalField(decimal_places=0, max_digits=10, verbose_name='پاداش سرشیفت'),
        ),
        migrations.AlterField(
            model_name='nezafatpadash',
            name='rank',
            field=models.IntegerField(verbose_name='رتبه'),
        ),
        migrations.AlterField(
            model_name='tolidpadash',
            name='description',
            field=models.TextField(verbose_name='شرح'),
        ),
        migrations.AlterField(
            model_name='tolidpadash',
            name='price_personnel',
            field=models.DecimalField(decimal_places=0, max_digits=10, verbose_name='پاداش پرسنل'),
        ),
        migrations.AlterField(
            model_name='tolidpadash',
            name='price_sarshift',
            field=models.DecimalField(decimal_places=0, max_digits=10, verbose_name='پاداش سرشیفت'),
        ),
        migrations.AlterField(
            model_name='tolidpadash',
            name='rank',
            field=models.IntegerField(verbose_name='رتبه'),
        ),
    ]
