# Generated by Django 3.2.6 on 2024-03-29 18:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mrp', '0051_auto_20240329_2110'),
    ]

    operations = [
        migrations.AddField(
            model_name='nezafatpadash',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mrp.financialprofile'),
        ),
        migrations.AddField(
            model_name='tolidpadash',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mrp.financialprofile'),
        ),
    ]
