# Generated by Django 3.2.6 on 2024-03-29 19:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mrp', '0052_auto_20240329_2229'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetrandemaninit',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mrp.financialprofile'),
        ),
        migrations.AddField(
            model_name='assetrandemanlist',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mrp.financialprofile'),
        ),
    ]
