# Generated by Django 3.2.6 on 2024-03-30 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mrp', '0054_auto_20240330_1029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nezafatranking',
            name='price_personnel',
            field=models.DecimalField(decimal_places=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='nezafatranking',
            name='price_sarshift',
            field=models.DecimalField(decimal_places=0, max_digits=10),
        ),
    ]
