# Generated by Django 3.2.6 on 2024-04-12 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mrp', '0055_auto_20240331_0023'),
    ]

    operations = [
        migrations.AddField(
            model_name='tolidpadash',
            name='mablagh_kol_randeman',
            field=models.DecimalField(decimal_places=0, default=1, max_digits=10, verbose_name='مبلغ کل راندمان'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tolidpadash',
            name='tolid_randeman',
            field=models.DecimalField(decimal_places=0, default=1, max_digits=10, verbose_name='راندمان تولید'),
            preserve_default=False,
        ),
    ]
