# Generated by Django 3.2.6 on 2024-04-12 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mrp', '0057_auto_20240412_1842'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialprofile',
            name='tolid_randeman_mazrab_3',
            field=models.DecimalField(decimal_places=0, default=1, max_digits=10, verbose_name='مضرب 3 راندمان'),
            preserve_default=False,
        ),
    ]
