# Generated by Django 3.2.6 on 2024-04-23 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mrp', '0059_alter_sysuser_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='failure',
            name='is_it_count',
            field=models.BooleanField(blank=True, null=True, verbose_name='فعال در محسابات'),
        ),
    ]
