# Generated by Django 3.2.6 on 2024-04-23 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mrp', '0061_alter_failure_is_it_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='failure',
            name='is_it_count',
            field=models.BooleanField(default=True, verbose_name='فعال در محسابات'),
        ),
    ]
