# Generated by Django 3.2.6 on 2024-05-29 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mrp', '0062_alter_failure_is_it_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assetrandemanpermonth',
            name='mah',
        ),
        migrations.RemoveField(
            model_name='assetrandemanpermonth',
            name='sal',
        ),
        migrations.AddField(
            model_name='assetrandemanpermonth',
            name='asset_randeman_list',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mrp.assetrandemanlist'),
        ),
        migrations.AlterField(
            model_name='shift',
            name='name',
            field=models.CharField(max_length=255, verbose_name='نام شیفت'),
        ),
    ]
