# Generated by Django 3.2.6 on 2024-05-29 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mrp', '0063_auto_20240529_2018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetrandemanpermonth',
            name='tolid_value',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
    ]
