# Generated by Django 3.2.6 on 2024-10-19 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mrp', '0064_alter_assetrandemanpermonth_tolid_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='assetVahed',
            field=models.IntegerField(blank=True, null=True, verbose_name='تعداد واحد'),
        ),
    ]
