# Generated by Django 3.2.6 on 2024-11-23 18:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mrp', '0065_assetcategory_assetmachinecategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='TolidPadash_V2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='شرح')),
                ('rank', models.IntegerField(verbose_name='رتبه')),
                ('price_personnel', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='پاداش پرسنل')),
                ('assetMachineCategory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mrp.machinecategory')),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mrp.financialprofile')),
            ],
            options={
                'db_table': 'tolidpadash_v2',
                'ordering': ('rank',),
            },
        ),
    ]
