# Generated by Django 3.2.6 on 2024-10-19 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mrp', '0066_dailyproduction_vahed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dailyproduction',
            old_name='counter',
            new_name='counter1',
        ),
        migrations.AddField(
            model_name='dailyproduction',
            name='counter2',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
