# Generated by Django 3.2.6 on 2024-11-10 05:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mrp', '0067_auto_20241019_1910'),
    ]

    operations = [
        migrations.AddField(
            model_name='zayeatvaz',
            name='makan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='zayeat_makan', to='mrp.asset'),
        ),
    ]
