# Generated by Django 3.2.6 on 2025-11-02 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mrp', '0068_auto_20250105_1220'),
    ]

    operations = [
        migrations.CreateModel(
            name='MachineCategory_Nezafat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='نام')),
                ('description', models.CharField(max_length=50, verbose_name='توضیحات')),
                ('isPartOf', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mrp.machinecategory_nezafat', verbose_name='زیر مجموعه')),
            ],
            options={
                'db_table': 'machinecategorynezafat',
            },
        ),
    ]
