# Generated by Django 3.2.6 on 2024-12-30 03:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mrp', '0068_assetdetail_color_entryform'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyproduction',
            name='moshakhase',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dailyproduction_shift', to='mrp.entryform'),
        ),
    ]
