# Generated by Django 3.2.6 on 2024-12-07 10:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mrp', '0069_auto_20241207_1052'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaserequest',
            name='consume_place',
        ),
        migrations.RemoveField(
            model_name='purchaserequest',
            name='description',
        ),
        migrations.AddField(
            model_name='requestitem',
            name='consume_place',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='consume_place', to='mrp.asset'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='requestitem',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
