# Generated by Django 3.2.6 on 2025-11-02 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mrp', '0069_machinecategory_nezafat'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='assetMachineCategory_nezafat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mrp.machinecategory_nezafat', verbose_name='نوع دستگاه'),
        ),
        migrations.CreateModel(
            name='NezafatPadash_V2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='شرح')),
                ('rank', models.IntegerField(verbose_name='رتبه')),
                ('price_personnel', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='پاداش پرسنل')),
                ('assetMachineCategory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mrp.machinecategory_nezafat')),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mrp.financialprofile')),
            ],
            options={
                'db_table': 'nezafatpadash_v2',
                'ordering': ('rank',),
            },
        ),
    ]
