# Generated by Django 3.2.6 on 2024-12-30 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mrp', '0069_dailyproduction_moshakhase'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyproduction',
            name='zayeat',
            field=models.FloatField(default=0),
        ),
    ]
