# Generated by Django 3.2.6 on 2025-01-04 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mrp', '0070_auto_20241207_1347'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestitem',
            name='price',
            field=models.FloatField(default=0),
        ),
    ]
