# Generated by Django 3.2.6 on 2025-11-02 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mrp', '0070_auto_20251102_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nezafatpadash_v2',
            name='assetMachineCategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mrp.machinecategory_nezafat', verbose_name='نوع دستگاه'),
        ),
    ]
