# Generated by Django 3.2.6 on 2024-12-30 06:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mrp', '0071_auto_20241230_0942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetdetail',
            name='asset_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mrp.assetcategory2'),
        ),
    ]
