# Generated by Django 3.2.6 on 2025-11-04 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mrp', '0071_alter_nezafatpadash_v2_assetmachinecategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='NezafatRanking_V2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField(choices=[(1, 'رتبه اول'), (2, 'رتبه دوم'), (3, 'رتبه سوم')])),
                ('price_sarshift', models.DecimalField(decimal_places=0, max_digits=10)),
                ('price_personnel', models.DecimalField(decimal_places=0, max_digits=10)),
                ('assetMachineCategory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mrp.machinecategory_nezafat', verbose_name='نوع دستگاه')),
                ('asset_randeman_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mrp.assetrandemanlist')),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mrp.shift')),
            ],
            options={
                'db_table': 'nezafatranking_v2',
            },
        ),
    ]
