# Generated by Django 3.2.6 on 2024-12-30 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mrp', '0072_alter_assetdetail_asset_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entryform',
            name='la',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='entryform',
            name='tool',
            field=models.IntegerField(),
        ),
    ]
