# Generated by Django 3.2.6 on 2025-11-05 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mrp', '0072_nezafatranking_v2'),
    ]

    operations = [
        migrations.AddField(
            model_name='machinecategory_nezafat',
            name='operator_count',
            field=models.IntegerField(default=0, verbose_name='تعداد اپراتور'),
        ),
    ]
