# Generated by Django 3.2.6 on 2025-01-07 06:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mrp', '0072_auto_20250107_0939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestitem',
            name='consume_place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consume_place', to='mrp.asset'),
        ),
    ]
