# Generated by Django 3.2.6 on 2025-01-03 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mrp', '0073_auto_20241230_1809'),
    ]

    operations = [
        migrations.AddField(
            model_name='zayeatvaz',
            name='moshakhase',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moshakhase_zayeat', to='mrp.entryform'),
        ),
        migrations.AlterField(
            model_name='assetdetail',
            name='nomre',
            field=models.FloatField(),
        ),
    ]
