# Generated by Django 3.2.6 on 2025-01-12 18:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mrp', '0074_auto_20250103_1744'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assetTypes', models.IntegerField(blank=True, choices=[(1, 'مکان'), (2, 'ماشین  آلات'), (3, 'ابزارآلات')], null=True, verbose_name='نوع دارایی')),
                ('assetName', models.CharField(max_length=100, verbose_name='مشخصات')),
                ('assetDescription', models.CharField(blank=True, max_length=100, null=True, verbose_name='توضیحات')),
                ('assetCode', models.CharField(blank=True, max_length=50, null=True, verbose_name='کد')),
                ('assetAddress', models.CharField(blank=True, max_length=100, null=True, verbose_name='آدرس')),
                ('assetCity', models.CharField(blank=True, max_length=50, null=True, verbose_name='شهر')),
                ('assetState', models.CharField(blank=True, max_length=50, null=True, verbose_name='استان')),
                ('assetZipcode', models.CharField(blank=True, max_length=50, null=True, verbose_name='کد پستی')),
                ('assetCountry', models.CharField(blank=True, max_length=100, null=True, verbose_name='کشور')),
                ('assetAccount', models.CharField(blank=True, max_length=100, null=True, verbose_name='حساب')),
                ('assetChargeDepartment', models.CharField(blank=True, max_length=100, null=True, verbose_name='دپارتمان مسوول')),
                ('assetNotes', models.CharField(blank=True, max_length=100, null=True, verbose_name='یادداشت')),
                ('assetBarcode', models.IntegerField(blank=True, null=True, verbose_name='بارکد')),
                ('assetHasPartOf', models.BooleanField(default=False)),
                ('assetAisel', models.IntegerField(blank=True, null=True, verbose_name='راهرو')),
                ('assetRow', models.IntegerField(blank=True, null=True, verbose_name='ردیف')),
                ('assetBin', models.IntegerField(blank=True, null=True, verbose_name='Bin')),
                ('assetManufacture', models.CharField(blank=True, max_length=50, null=True, verbose_name='سازنده')),
                ('assetModel', models.CharField(blank=True, max_length=50, null=True, verbose_name='مدل')),
                ('assetSerialNumber', models.CharField(blank=True, max_length=50, null=True, verbose_name='شماره سریال')),
                ('assetStatus', models.BooleanField(default=True, verbose_name='وضعیت')),
                ('assetIsStock', models.BooleanField(default=False, verbose_name='انبار')),
                ('assetTavali', models.IntegerField(blank=True, null=True, verbose_name='شماره توالی')),
                ('assetVahed', models.IntegerField(blank=True, null=True, verbose_name='تعداد واحد')),
                ('assetCategory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mrp.assetcategory', verbose_name='دسته بندی')),
                ('assetIsLocatedAt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='location', to='mrp.asset2', verbose_name='مکان')),
                ('assetIsPartOf', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mrp.asset2', verbose_name='زیر مجموعه')),
                ('assetMachineCategory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mrp.machinecategory', verbose_name='نوع دستگاه')),
            ],
            options={
                'db_table': 'assets2',
                'ordering': ('assetTavali', 'assetName'),
            },
        ),
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partName', models.CharField(max_length=100, verbose_name='مشخصات')),
                ('partDescription', models.CharField(max_length=100, verbose_name='توضیحات')),
                ('partCode', models.CharField(max_length=50, verbose_name='کد')),
                ('partMake', models.CharField(blank=True, max_length=100, null=True, verbose_name='ساخته شده توسط')),
                ('partModel', models.CharField(blank=True, max_length=50, null=True, verbose_name='مدل')),
                ('partLastPrice', models.FloatField(blank=True, default=0, null=True, verbose_name='آخرین قیمت')),
                ('partAccount', models.CharField(blank=True, max_length=100, null=True, verbose_name='حساب')),
                ('partChargeDepartment', models.CharField(blank=True, max_length=100, null=True, verbose_name='دپارتمان مسوول')),
                ('partNotes', models.CharField(blank=True, max_length=100, null=True, verbose_name='یادداشت')),
                ('partBarcode', models.IntegerField(blank=True, null=True, verbose_name='بارکد')),
                ('partInventoryCode', models.CharField(blank=True, max_length=50, null=True, verbose_name='کد قفسه')),
            ],
            options={
                'db_table': 'parts',
                'ordering': ('partName',),
            },
        ),
        migrations.CreateModel(
            name='PartCsvFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msgFile', models.FileField(max_length=200, upload_to='documents/%Y/%m/%d')),
                ('msgFiledateAdded', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'partcsvfile',
            },
        ),
        migrations.CreateModel(
            name='PurchaseRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(default=django.utils.timezone.now)),
                ('is_emergency', models.BooleanField(default=False)),
                ('viewed_by', models.TextField(blank=True, default='[]')),
                ('status', models.CharField(choices=[('Pending', 'درخواست شده'), ('Approved', 'تایید شده'), ('Rejected', 'رد شده'), ('Ordered', 'سفارش دهده شده')], default='Pending', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='RequestItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.FloatField(default=0)),
                ('quantity', models.PositiveIntegerField()),
                ('consume_place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consume_place', to='mrp.asset2')),
                ('item_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consume_place', to='mrp.part')),
                ('purchase_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='mrp.purchaserequest')),
            ],
        ),
        migrations.CreateModel(
            name='RFQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('issued_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rfqs', to=settings.AUTH_USER_MODEL)),
                ('items', models.ManyToManyField(related_name='rfqs', to='mrp.RequestItem')),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('provided_items', models.ManyToManyField(blank=True, help_text='Items that this supplier can provide', related_name='potential_suppliers', to='mrp.RequestItem')),
            ],
        ),
        migrations.AlterModelOptions(
            name='sysuser',
            options={'ordering': ['title'], 'permissions': [('can_view_dashboard', 'can view dashboard'), ('can_admin_purchase', 'can admin create purchase'), ('view_all_request', 'can view  all purchase request')]},
        ),
        migrations.CreateModel(
            name='SupplierResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_terms', models.TextField()),
                ('arrival_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('rfq', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='mrp.rfq')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='mrp.supplier')),
            ],
        ),
        migrations.AddField(
            model_name='rfq',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rfqs', to='mrp.supplier'),
        ),
        migrations.AddField(
            model_name='requestitem',
            name='supplier_assigned',
            field=models.ForeignKey(blank=True, help_text='Supplier who can provide this item', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_items', to='mrp.supplier'),
        ),
        migrations.CreateModel(
            name='PurchaseRequestFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='purchase_requests/files/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('purchase_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='mrp.purchaserequest')),
            ],
        ),
        migrations.AddField(
            model_name='purchaserequest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_requests', to='mrp.sysuser'),
        ),
        migrations.CreateModel(
            name='PartUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PartUserPartId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mrp.part', verbose_name='قطعه')),
                ('PartUserUserId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mrp.sysuser', verbose_name='کاربر ')),
            ],
            options={
                'db_table': 'partuser',
            },
        ),
        migrations.CreateModel(
            name='PartFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partFile', models.FileField(max_length=200, upload_to='documents/')),
                ('partFiledateAdded', models.DateTimeField(auto_now_add=True)),
                ('partFilePartId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mrp.part')),
            ],
            options={
                'db_table': 'partfile',
            },
        ),
        migrations.CreateModel(
            name='PartCategory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, verbose_name='نام')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='کد')),
                ('description', models.CharField(max_length=50, verbose_name='توضیحات')),
                ('priority', models.IntegerField(null=True, verbose_name='اولویت')),
                ('isPartOf', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mrp.partcategory', verbose_name='زیر مجموعه')),
            ],
            options={
                'db_table': 'partcategory',
            },
        ),
        migrations.AddField(
            model_name='part',
            name='partCategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dasdadassa', to='mrp.partcategory', verbose_name='دسته بندی'),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_terms', models.TextField()),
                ('arrival_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('items', models.ManyToManyField(related_name='orders', to='mrp.RequestItem')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='mrp.supplier')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='mrp.comment')),
                ('purchase_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='mrp.purchaserequest')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mrp.sysuser')),
            ],
        ),
    ]
