# Generated by Django 3.2.6 on 2025-01-07 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mrp', '0074_alter_requestitem_consume_place'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sysuser',
            options={'ordering': ['title'], 'permissions': [('can_view_dashboard', 'can view dashboard'), ('can_admin_purchase', 'can admin create purchase')]},
        ),
    ]
