# Generated by Django 3.2.6 on 2025-01-09 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mrp', '0075_alter_sysuser_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaserequest',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
