# Generated by Django 3.2.6 on 2025-01-17 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mrp', '0075_auto_20250112_2222'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sysuser',
            options={'ordering': ['title'], 'permissions': [('can_view_dashboard', 'can view dashboard'), ('can_admin_purchase', 'can admin create purchase'), ('view_all_request', 'can view  all purchase request'), ('can_operator_mrp', 'mrp user operator')]},
        ),
    ]
