# Generated by Django 3.2.6 on 2025-01-09 16:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mrp', '0076_alter_purchaserequest_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseRequestFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='purchase_requests/files/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('purchase_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='mrp.purchaserequest')),
            ],
        ),
    ]
