# Generated by Django 3.2.6 on 2025-01-17 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mrp', '0077_alter_sysuser_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaserequest',
            name='status',
            field=models.CharField(choices=[('Pending', 'درخواست شده'), ('Approved', 'تایید انبار'), ('Rejected', 'رد شده'), ('Ordered', 'سفارش دهده شده'), ('Approved2', 'تایید مهندس فرهادی'), ('Approved3', 'تایید مدیریت')], default='Pending', max_length=20),
        ),
    ]
