# Generated by Django 3.2.6 on 2025-01-10 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mrp', '0078_purchaserequest_is_emergency'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaserequest',
            name='viewed_by',
            field=models.TextField(blank=True, default='[]'),
        ),
    ]
