# Generated by Django 3.2.6 on 2025-01-11 11:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mrp', '0079_purchaserequest_viewed_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaserequest',
            name='created_at',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
