# Generated by Django 3.2.6 on 2025-04-24 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mrp', '0080_alter_purchaserequest_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetdetail',
            name='tab',
            field=models.FloatField(default=0),
        ),
    ]
