# Generated by Django 3.2.6 on 2025-04-24 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mrp', '0081_assetdetail_tab'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetdetail',
            name='tab',
            field=models.FloatField(default=1),
        ),
    ]
