# Generated by Django 3.2.6 on 2025-01-12 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mrp', '0081_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sysuser',
            options={'ordering': ['title'], 'permissions': [('can_view_dashboard', 'can view dashboard'), ('can_admin_purchase', 'can admin create purchase'), ('view_all_request', 'can view  all purchase request')]},
        ),
        migrations.AlterField(
            model_name='purchaserequest',
            name='status',
            field=models.CharField(choices=[('Pending', 'تستست'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Ordered', 'Ordered')], default='Pending', max_length=20),
        ),
    ]
