# Generated by Django 3.2.6 on 2025-01-12 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mrp', '0082_auto_20250112_2156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaserequest',
            name='status',
            field=models.CharField(choices=[('Pending', 'درخواست شده'), ('Approved', 'تایید شده'), ('Rejected', 'رد شده'), ('Ordered', 'سفارش دهده شده')], default='Pending', max_length=20),
        ),
    ]
