# Generated by Django 3.2.6 on 2025-04-24 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mrp', '0082_alter_assetdetail_tab'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyproduction',
            name='tab',
            field=models.FloatField(default=1),
        ),
    ]
