# Generated by Django 3.2.6 on 2025-04-26 11:01

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mrp', '0083_dailyproduction_tab'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('photos', 'عکس\u200cهای قبل/بعد'), ('readings', 'قرائت\u200cهای تجهیزات'), ('measurements', 'اندازه\u200cگیری\u200cها'), ('signature', 'امضای تکنسین')], max_length=50, unique=True, verbose_name='نوع مستند')),
            ],
            options={
                'verbose_name': 'نوع مستند',
                'verbose_name_plural': 'انواع مستندات',
            },
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام تجهیزات')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='کد تجهیزات')),
            ],
            options={
                'verbose_name': 'تجهیزات',
                'verbose_name_plural': 'تجهیزات',
            },
        ),
        migrations.CreateModel(
            name='Maintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('maintenance_type', models.CharField(choices=[('manual', 'دستی'), ('recurring', 'دوره\u200cای'), ('emergency', 'اضطراری')], max_length=20, verbose_name='نوع نگهداری')),
                ('operation_type', models.CharField(choices=[('preventive', 'نگهداری پیشگیرانه'), ('corrective', 'اصلاحی'), ('inspection', 'بازرسی'), ('breakdown', 'خرابی'), ('calibration', 'کالیبراسیون'), ('lubrication', 'روغن\u200cکاری'), ('safety_check', 'بررسی ایمنی')], max_length=50, verbose_name='نوع عملیات')),
                ('priority', models.CharField(choices=[('High', 'بالا'), ('Medium', 'متوسط'), ('Low', 'پایین')], default='Medium', max_length=20, verbose_name='اولویت')),
                ('created_date', models.DateField(default=django.utils.timezone.now, verbose_name='تاریخ ایجاد')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='تاریخ سررسید')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='تاریخ شروع')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='تاریخ پایان')),
                ('recurrence', models.CharField(blank=True, choices=[('daily', 'روزانه'), ('weekly', 'هفتگی'), ('monthly', 'ماهانه'), ('quarterly', 'فصلی'), ('yearly', 'سالانه')], max_length=20, null=True, verbose_name='دوره تکرار')),
                ('last_work_order_date', models.DateField(blank=True, null=True, verbose_name='آخرین تاریخ تولید دستور کار')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('problem_description', models.TextField(blank=True, verbose_name='شرح مشکل')),
                ('reported_by', models.CharField(blank=True, max_length=100, verbose_name='گزارش\u200cدهنده')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('safety_instructions', models.TextField(blank=True, verbose_name='دستورالعمل\u200cهای ایمنی')),
                ('completion_notes', models.TextField(blank=True, verbose_name='یادداشت\u200cهای تکمیل')),
                ('approval_required', models.BooleanField(default=True, verbose_name='نیاز به تأیید')),
                ('approval_role', models.CharField(choices=[('supervisor', 'سرپرست نگهداری'), ('manager', 'مدیر نگهداری'), ('engineer', 'مهندس نگهداری'), ('custom', 'نقش سفارشی')], default='supervisor', max_length=50, verbose_name='نقش تأییدکننده')),
                ('status', models.CharField(choices=[('pending', 'در انتظار'), ('in_progress', 'در حال انجام'), ('completed', 'تکمیل شده'), ('approved', 'تأیید شده')], default='pending', max_length=20, verbose_name='وضعیت')),
                ('is_visible', models.BooleanField(default=True, verbose_name='قابل مشاهده')),
                ('visible_from', models.DateField(blank=True, null=True, verbose_name='قابل مشاهده از تاریخ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
            ],
            options={
                'verbose_name': 'نگهداری',
                'verbose_name_plural': 'نگهداری\u200cها',
            },
        ),
        migrations.CreateModel(
            name='Technician',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام تکنسین')),
                ('employee_id', models.CharField(max_length=50, unique=True, verbose_name='کد پرسنلی')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='ایمیل')),
            ],
            options={
                'verbose_name': 'تکنسین',
                'verbose_name_plural': 'تکنسین\u200cها',
            },
        ),
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام ابزار')),
                ('maintenance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tools', to='mrp.maintenance', verbose_name='نگهداری')),
            ],
            options={
                'verbose_name': 'ابزار',
                'verbose_name_plural': 'ابزارها',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_type', models.CharField(choices=[('single', 'وظیفه تک\u200cگزینه\u200cای'), ('checklist', 'چک لیست'), ('group', 'گروه وظایف')], max_length=20, verbose_name='نوع وظیفه')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب')),
                ('maintenance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='mrp.maintenance', verbose_name='نگهداری')),
            ],
            options={
                'verbose_name': 'وظیفه',
                'verbose_name_plural': 'وظایف',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SparePart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام قطعه')),
                ('part_code', models.CharField(max_length=50, unique=True, verbose_name='کد قطعه')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='تعداد')),
                ('maintenance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spare_parts', to='mrp.maintenance', verbose_name='نگهداری')),
            ],
            options={
                'verbose_name': 'قطعه یدکی',
                'verbose_name_plural': 'قطعات یدکی',
            },
        ),
        migrations.AddField(
            model_name='maintenance',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mrp.technician', verbose_name='اختصاص به'),
        ),
        migrations.AddField(
            model_name='maintenance',
            name='documentation',
            field=models.ManyToManyField(blank=True, to='mrp.DocumentationType', verbose_name='مستندات'),
        ),
        migrations.AddField(
            model_name='maintenance',
            name='equipment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mrp.equipment', verbose_name='تجهیزات'),
        ),
        migrations.CreateModel(
            name='GroupTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200, verbose_name='توضیحات زیروظیفه')),
                ('subtask_type', models.CharField(choices=[('checkbox', 'چک باکس ساده'), ('checklist', 'چک لیست'), ('measurement', 'اندازه\u200cگیری')], max_length=20, verbose_name='نوع زیروظیفه')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_tasks', to='mrp.task', verbose_name='وظیفه')),
            ],
            options={
                'verbose_name': 'زیروظیفه گروه',
                'verbose_name_plural': 'زیروظایف گروه',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ChecklistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200, verbose_name='توضیحات آیتم')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist_items', to='mrp.task', verbose_name='وظیفه')),
            ],
            options={
                'verbose_name': 'آیتم چک\u200cلیست',
                'verbose_name_plural': 'آیتم\u200cهای چک\u200cلیست',
                'ordering': ['order'],
            },
        ),
        migrations.AddIndex(
            model_name='maintenance',
            index=models.Index(fields=['maintenance_type', 'is_visible', 'due_date'], name='mrp_mainten_mainten_42ce82_idx'),
        ),
        migrations.AddIndex(
            model_name='maintenance',
            index=models.Index(fields=['is_active', 'recurrence'], name='mrp_mainten_is_acti_8efc2b_idx'),
        ),
    ]
