# Generated by Django 3.2.6 on 2025-12-02 21:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mrp', '0085_alter_asset_assetcategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='assetCategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asset_set', to='mrp.assetcategory', verbose_name='دسته بندی'),
        ),
    ]
