# Generated by Django 3.2.6 on 2025-01-13 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mrp', '0087_alter_sysuser_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaserequest',
            name='status',
            field=models.CharField(choices=[('Pending', 'درخواست شده'), ('Approved', 'تایید شده'), ('Rejected', 'رد شده'), ('Ordered', 'سفارش داده شده'), ('Approve2', 'تایید دوم'), ('Approve3', 'تایید سوم')], default='Pending', max_length=20),
        ),
    ]
