# Generated by Django 3.2.6 on 2025-01-18 08:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mrp', '0091_auto_20250114_1025'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseNotes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('purchase_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='mrp.purchaserequest')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mrp.sysuser')),
            ],
        ),
    ]
