# Generated by Django 3.2.6 on 2025-01-18 09:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mrp', '0093_purchaseactivitylog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseactivitylog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mrp.sysuser'),
        ),
    ]
