# Generated by Django 3.2.6 on 2025-01-18 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mrp', '0094_alter_purchaseactivitylog_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaserequest',
            name='status',
            field=models.CharField(choices=[('Pending', 'درخواست شده'), ('Approved', 'تایید انبار'), ('Rejected', 'رد شده'), ('Ordered', 'سفارش '), ('Approve2', 'تایید مهندس اعزامی'), ('Approve3', 'تایید مهندس ارزنده'), ('Purchased', 'خریداری شد')], default='Pending', max_length=20),
        ),
    ]
