# Generated by Django 3.2.6 on 2025-01-26 05:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mrp', '0097_alter_sysuser_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sysuser',
            options={'ordering': ['title'], 'permissions': [('can_view_dashboard', 'can view dashboard'), ('can_admin_purchase', 'can admin create purchase'), ('view_all_request', 'can view  all purchase request'), ('can_confirm_request', 'can confirm request'), ('can_operator_mrp', 'mrp user operator'), ('can_operator_purchase', 'purchase user operator'), ('can_edit_purchase', 'user can edit purchase'), ('can_view_faktors', 'user can view faktors'), ('can_upload_faktors', 'user can upload faktors'), ('can_create_paraf', 'user can craete paraf'), ('can_view_paraf', 'user can view paraf')]},
        ),
        migrations.AddField(
            model_name='purchaserequest',
            name='manager_comment',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='requestitem',
            name='item_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consume_part', to='mrp.part'),
        ),
        migrations.CreateModel(
            name='PurchaseRequestFaktor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='purchase_requests/faktors/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('purchase_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faktors', to='mrp.purchaserequest')),
            ],
        ),
    ]
