# Generated by Django 3.2.6 on 2025-01-31 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mrp', '0098_auto_20250126_0912'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestitem',
            name='supplied_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
