# Generated by Django 3.2.6 on 2025-02-16 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mrp', '0099_requestitem_supplied_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaserequest',
            name='status',
            field=models.CharField(choices=[('Pending', 'درخواست شده'), ('Approved', 'تایید انبار'), ('Rejected', 'رد شده'), ('Ordered', 'سفارش '), ('Approve2', 'تایید مهندس اعزامی'), ('Approve3', 'تایید مهندس ارزنده'), ('Purchased', 'خریداری شد'), ('Approve4', 'تایید بازرگانی')], default='Pending', max_length=20),
        ),
    ]
