# Generated by Django 3.2.6 on 2025-02-21 09:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mrp', '0100_alter_purchaserequest_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='rfq',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rfq',
            name='total_price',
            field=models.DecimalField(decimal_places=0, default=None, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='rfq',
            name='issued_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rfquser', to='mrp.sysuser'),
        ),
        migrations.AlterField(
            model_name='rfq',
            name='items',
            field=models.ManyToManyField(related_name='rfqitem', to='mrp.RequestItem'),
        ),
        migrations.AlterField(
            model_name='rfq',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rfqsupplier', to='mrp.supplier'),
        ),
    ]
