# Generated by Django 3.2.6 on 2025-02-21 10:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mrp', '0101_auto_20250221_1319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rfq',
            name='issued_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rfquser', to='mrp.sysuser'),
        ),
    ]
