# Generated by Django 3.2.6 on 2025-02-21 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mrp', '0102_alter_rfq_issued_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rfq',
            name='items',
        ),
        migrations.AddField(
            model_name='rfq',
            name='items',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rfqitem', to='mrp.requestitem'),
        ),
    ]
