# Generated by Django 3.2.6 on 2025-02-24 08:21

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mrp', '0105_rfq_is_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaserequest',
            name='status',
            field=models.CharField(choices=[('Pending', 'درخواست شده'), ('Approved', 'تایید انبار'), ('Rejected', 'رد شده'), ('Ordered', 'سفارش '), ('Approve2', 'تایید مهندس اعزامی'), ('Approve3', 'تایید مهندس ارزنده'), ('Purchased', 'خریداری شد'), ('Approve4', 'تایید بازرگانی'), ('GuardApproved', 'تأیید نگهبانی'), ('Completed', 'کامل شده')], default='Pending', max_length=20),
        ),
        migrations.CreateModel(
            name='GoodsEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_date', models.DateField(default=django.utils.timezone.now)),
                ('quantity_received', models.PositiveIntegerField(help_text='تعداد کالای وارد شده در این ورود')),
                ('guard_approved', models.BooleanField(default=False, help_text='تأیید شده توسط نگهبانی')),
                ('guard_comment', models.TextField(blank=True, help_text='توضیحات نگهبان در صورت رد', null=True)),
                ('request_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='mrp.requestitem')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivered_entries', to='mrp.supplier')),
            ],
        ),
    ]
