# Generated by Django 3.2.6 on 2025-03-02 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mrp', '0107_auto_20250225_1301'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaserequest',
            name='is_tamiri',
            field=models.BooleanField(default=False),
        ),
    ]
