# Generated by Django 3.2.6 on 2025-04-13 18:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mrp', '0110_auto_20250413_1725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billofmaterials',
            name='components',
            field=models.ManyToManyField(blank=True, null=True, related_name='used_in_boms', through='mrp.BOMComponent', to='mrp.Product'),
        ),
        migrations.AlterField(
            model_name='billofmaterials',
            name='product',
            field=models.ForeignKey(limit_choices_to={'product_type': 'finished'}, on_delete=django.db.models.deletion.CASCADE, related_name='boms', to='mrp.product', verbose_name='محصول'),
        ),
        migrations.AlterField(
            model_name='billofmaterials',
            name='reference',
            field=models.CharField(max_length=50, unique=True, verbose_name='کد'),
        ),
    ]
