# Generated by Django 3.2.6 on 2025-04-14 07:13

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mrp', '0111_auto_20250413_2208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billofmaterials',
            name='operation_time',
            field=models.FloatField(help_text='Time in minutes', validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='زمان عملیات'),
        ),
        migrations.AlterField(
            model_name='bomcomponent',
            name='product',
            field=models.ForeignKey(limit_choices_to={'product_type': 'component'}, on_delete=django.db.models.deletion.CASCADE, to='mrp.product'),
        ),
    ]
