# Generated by Django 3.2.6 on 2025-04-16 10:45

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mrp', '0112_auto_20250414_1043'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkCenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('capacity_per_hour', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)])),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='bomcomponent',
            name='product',
            field=models.ForeignKey(limit_choices_to={'product_type': 'component'}, on_delete=django.db.models.deletion.CASCADE, to='mrp.product', verbose_name='محصول'),
        ),
        migrations.AlterField(
            model_name='bomcomponent',
            name='quantity',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='تعداد'),
        ),
        migrations.AlterField(
            model_name='bomcomponent',
            name='uom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mrp.unitofmeasure', verbose_name='واحد اندازه گیری'),
        ),
    ]
