# Generated by Django 3.2.6 on 2025-04-17 14:00

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mrp', '0113_auto_20250416_1415'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManufacturingOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=50, unique=True)),
                ('quantity_to_produce', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)])),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('confirmed', 'Confirmed'), ('in_progress', 'In Progress'), ('done', 'Done'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('scheduled_date', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mrp.billofmaterials')),
                ('product_to_manufacture', models.ForeignKey(limit_choices_to={'product_type': 'finished'}, on_delete=django.db.models.deletion.CASCADE, to='mrp.product')),
                ('responsible', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mrp.sysuser')),
            ],
            options={
                'ordering': ['-scheduled_date', 'reference'],
            },
        ),
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.PositiveIntegerField(help_text='Order in which this operation is performed')),
                ('name', models.CharField(help_text='Name of the operation', max_length=200)),
                ('duration', models.FloatField(help_text='Expected duration in hours', validators=[django.core.validators.MinValueValidator(0.0)])),
                ('instructions', models.TextField(blank=True, help_text='Instructions for the operator')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['sequence', 'name'],
            },
        ),
        migrations.AlterField(
            model_name='workcenter',
            name='active',
            field=models.BooleanField(default=True, verbose_name='فعال'),
        ),
        migrations.AlterField(
            model_name='workcenter',
            name='capacity_per_hour',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='ظرفیت بر ساعت'),
        ),
        migrations.AlterField(
            model_name='workcenter',
            name='code',
            field=models.CharField(max_length=50, unique=True, verbose_name='کد'),
        ),
        migrations.AlterField(
            model_name='workcenter',
            name='name',
            field=models.CharField(max_length=200, verbose_name='نام'),
        ),
        migrations.CreateModel(
            name='WorkOrderTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True, help_text='Optional description of the template')),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bom', models.ForeignKey(help_text='BoM this template is associated with', on_delete=django.db.models.deletion.CASCADE, related_name='work_order_templates', to='mrp.billofmaterials')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='WorkOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.FloatField(help_text='Duration in hours', validators=[django.core.validators.MinValueValidator(0.0)])),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('in_progress', 'In Progress'), ('done', 'Done'), ('cancelled', 'Cancelled')], default='planned', max_length=20)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('manufacturing_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_orders', to='mrp.manufacturingorder')),
                ('operation', models.ForeignKey(blank=True, help_text='Operation from template this work order is based on', null=True, on_delete=django.db.models.deletion.SET_NULL, to='mrp.operation')),
                ('work_center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mrp.workcenter')),
            ],
            options={
                'ordering': ['start_date'],
            },
        ),
        migrations.AddField(
            model_name='operation',
            name='work_center',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mrp.workcenter'),
        ),
        migrations.AddField(
            model_name='operation',
            name='work_order_template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operations', to='mrp.workordertemplate'),
        ),
        migrations.AddField(
            model_name='manufacturingorder',
            name='work_order_template',
            field=models.ForeignKey(blank=True, help_text='Template for generating work orders', null=True, on_delete=django.db.models.deletion.SET_NULL, to='mrp.workordertemplate'),
        ),
        migrations.AddConstraint(
            model_name='workordertemplate',
            constraint=models.UniqueConstraint(fields=('bom', 'code'), name='unique_template_per_bom'),
        ),
        migrations.AddConstraint(
            model_name='workorder',
            constraint=models.CheckConstraint(check=models.Q(('duration__gt', 0)), name='work_order_duration_positive'),
        ),
        migrations.AddConstraint(
            model_name='operation',
            constraint=models.UniqueConstraint(fields=('work_order_template', 'sequence'), name='unique_sequence_per_template'),
        ),
        migrations.AddConstraint(
            model_name='operation',
            constraint=models.CheckConstraint(check=models.Q(('duration__gt', 0)), name='duration_positive'),
        ),
        migrations.AddConstraint(
            model_name='manufacturingorder',
            constraint=models.CheckConstraint(check=models.Q(('quantity_to_produce__gt', 0)), name='quantity_to_produce_positive'),
        ),
    ]
