# Generated by Django 3.2.6 on 2025-04-18 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mrp', '0114_auto_20250417_1730'),
    ]

    operations = [
        migrations.AddField(
            model_name='manufacturingorder',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
