# Generated by Django 3.2.6 on 2025-05-07 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mrp', '0115_manufacturingorder_notes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sysuser',
            options={'ordering': ['title'], 'permissions': [('can_view_dashboard', 'can view dashboard'), ('can_admin_purchase', 'can admin create purchase'), ('view_all_request', 'can view  all purchase request'), ('can_confirm_request', 'can confirm request'), ('can_operator_mrp', 'mrp user operator'), ('can_operator_purchase', 'purchase user operator'), ('can_edit_purchase', 'user can edit purchase'), ('can_view_faktors', 'user can view faktors'), ('can_upload_faktors', 'user can upload faktors'), ('can_create_paraf', 'user can craete paraf'), ('can_view_paraf', 'user can view paraf'), ('can_edit_rfq', 'user can edit rfq'), ('can_view_rfq', 'user can view rfq'), ('can_operate_guard', 'user can operate gaurd'), ('can_view_pb', 'user can view planning board')]},
        ),
    ]
