# Generated by Django 3.2.6 on 2025-05-12 06:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mrp', '0116_alter_sysuser_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetCategory2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='نام')),
                ('code', models.CharField(max_length=50, verbose_name='کد')),
                ('description', models.CharField(max_length=50, verbose_name='توضیحات')),
                ('priority', models.IntegerField(null=True, verbose_name='اولویت')),
                ('isPartOf', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mrp.assetcategory2', verbose_name='زیر مجموعه')),
            ],
            options={
                'db_table': 'assetcategory2',
                'ordering': ('priority',),
            },
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='EntryForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('tool', models.IntegerField()),
                ('la', models.IntegerField()),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mrp.color')),
            ],
        ),
        migrations.CreateModel(
            name='AssetDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomre', models.FloatField()),
                ('speed', models.FloatField()),
                ('tab', models.FloatField(default=1)),
                ('asset_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mrp.assetcategory2')),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asset_details', to='mrp.entryform')),
            ],
        ),
    ]
