# Generated by Django 3.2.6 on 2025-05-18 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mrp', '0117_assetcategory2_assetdetail_color_entryform'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Full name or company name of the customer', max_length=100)),
                ('email', models.EmailField(blank=True, help_text="Customer's contact email", max_length=254, null=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddConstraint(
            model_name='customer',
            constraint=models.UniqueConstraint(fields=('name', 'email'), name='unique_customer_name_email'),
        ),
    ]
