# Generated by Django 3.2.6 on 2025-06-01 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mrp', '0117_assetcategory2_assetdetail_color_entryform'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='to_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='to_user', to='mrp.sysuser'),
        ),
        migrations.AlterField(
            model_name='purchaserequest',
            name='status',
            field=models.CharField(choices=[('Pending', 'درخواست شده'), ('Approved', 'تایید انبار'), ('Rejected', 'رد شده'), ('Ordered', 'سفارش '), ('Approve2', 'تایید مدیر تولید'), ('Approve3', 'تایید مهندس ارزنده'), ('Purchased', 'خریداری شد'), ('Approve4', 'تایید بازرگانی'), ('GuardApproved', 'ورود ناقص'), ('Completed', 'کامل شده')], default='Pending', max_length=20),
        ),
    ]
