# Generated by Django 3.2.6 on 2025-07-03 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mrp', '0118_auto_20250601_1933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='part',
            name='partCode',
            field=models.CharField(max_length=100, verbose_name='کد'),
        ),
    ]
