# Generated by Django 3.2.6 on 2025-05-18 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mrp', '0118_auto_20250518_1324'),
    ]

    operations = [
        migrations.AddField(
            model_name='manufacturingorder',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mrp.customer'),
        ),
    ]
