# Generated by Django 3.2.6 on 2025-07-19 05:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mrp', '0119_alter_part_partcode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='to_user',
        ),
        migrations.AddField(
            model_name='purchaserequest',
            name='rejected_at',
            field=models.DateTimeField(blank=True, help_text='زمان رد درخواست', null=True),
        ),
        migrations.AddField(
            model_name='purchaserequest',
            name='rejected_by',
            field=models.ForeignKey(blank=True, help_text='کاربری که درخواست را رد کرده', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rejected_purchase_requests', to='mrp.sysuser'),
        ),
        migrations.AddField(
            model_name='purchaserequest',
            name='rejection_reason',
            field=models.TextField(blank=True, help_text='دلیل رد درخواست', null=True),
        ),
    ]
