# Generated by Django 3.2.6 on 2025-07-19 05:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mrp', '0120_auto_20250719_0839'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='to_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='to_user', to='mrp.sysuser'),
        ),
    ]
