# Generated by Django 3.2.6 on 2025-07-22 09:36

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mrp', '0121_comment_to_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseRejectionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_status', models.CharField(help_text='وضعیت درخواست قبل از رد', max_length=20)),
                ('new_status', models.CharField(help_text='وضعیت جدید درخواست پس از رد', max_length=20)),
                ('rejection_reason', models.TextField(help_text='دلیل رد درخواست')),
                ('rejected_at', models.DateTimeField(default=django.utils.timezone.now, help_text='زمان رد درخواست')),
                ('purchase_request', models.ForeignKey(help_text='درخواست خرید مرتبط', on_delete=django.db.models.deletion.CASCADE, related_name='rejection_history', to='mrp.purchaserequest')),
                ('rejected_by', models.ForeignKey(blank=True, help_text='کاربری که درخواست را رد کرده', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rejection_actions', to='mrp.sysuser')),
            ],
        ),
    ]
