# Generated by Django 3.2.6 on 2025-06-04 08:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mrp', '0121_calendarevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendarevent',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='calendarevent',
            name='type',
            field=models.CharField(default='appointment', max_length=50),
        ),
        migrations.AlterField(
            model_name='calendarevent',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='calendar_events', to='mrp.manufacturingorder'),
        ),
        migrations.AlterField(
            model_name='calendarevent',
            name='quantity',
            field=models.FloatField(default=0),
        ),
    ]
