# Generated by Django 3.2.6 on 2025-06-04 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mrp', '0122_auto_20250604_1214'),
    ]

    operations = [
        migrations.AddField(
            model_name='manufacturingorder',
            name='line',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orderd_line', to='mrp.line'),
        ),
    ]
