# Generated by Django 3.2.6 on 2025-07-22 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mrp', '0122_purchaserejectionhistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaserequest',
            name='status',
            field=models.CharField(choices=[('Pending', 'درخواست شده'), ('Approved', 'تایید انبار'), ('Ordered', 'سفارش '), ('Approve2', 'تایید مدیر تولید'), ('Approve3', 'تایید مهندس ارزنده'), ('Purchased', 'خریداری شد'), ('Approve4', 'تایید بازرگانی'), ('GuardApproved', 'ورود ناقص'), ('Completed', 'کامل شده')], default='Pending', max_length=20),
        ),
    ]
