# Generated by Django 3.2.6 on 2025-06-04 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mrp', '0123_manufacturingorder_line'),
    ]

    operations = [
        migrations.AddField(
            model_name='manufacturingorder',
            name='first_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='manufacturingorder',
            name='second_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
