# Generated by Django 3.2.6 on 2025-07-29 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mrp', '0123_alter_purchaserequest_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Personnel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Pid', models.CharField(max_length=20)),
                ('PNumber', models.CharField(max_length=20)),
                ('CpCode', models.CharField(max_length=100)),
                ('CardNo', models.CharField(max_length=100)),
                ('FName', models.CharField(max_length=100)),
                ('LName', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Personnel',
                'db_table': 'personnel',
            },
        ),
    ]
