# Generated by Django 3.2.6 on 2025-08-10 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mrp', '0124_operator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyproduction',
            name='counter1',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='dailyproduction',
            name='counter2',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
