# Generated by Django 3.2.6 on 2025-06-04 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mrp', '0124_auto_20250604_2340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manufacturingorder',
            name='first_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='manufacturingorder',
            name='scheduled_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='manufacturingorder',
            name='second_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
