# Generated by Django 3.2.6 on 2025-08-10 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mrp', '0125_auto_20250810_1025'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyproduction',
            name='operators_data',
            field=models.TextField(blank=True, help_text='JSON data containing multiple operators', null=True),
        ),
    ]
