# Generated by Django 3.2.6 on 2025-10-18 07:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mrp', '0125_auto_20250604_2357'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='calendarevent',
            options={'ordering': ['event_date', 'line'], 'verbose_name': 'رویداد تقویم', 'verbose_name_plural': 'رویدادهای تقویم'},
        ),
        migrations.AddField(
            model_name='calendarevent',
            name='line',
            field=models.ForeignKey(default=None, help_text='خط تولیدی که این رویداد در آن اجرا می\u200cشود', on_delete=django.db.models.deletion.CASCADE, related_name='calendar_events', to='mrp.line', verbose_name='خط تولید'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bomcomponent',
            name='product',
            field=models.ForeignKey(limit_choices_to={'product_type__in': ['component', 'raw']}, on_delete=django.db.models.deletion.CASCADE, to='mrp.product', verbose_name='محصول'),
        ),
        migrations.AlterField(
            model_name='calendarevent',
            name='description',
            field=models.TextField(blank=True, verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='calendarevent',
            name='event_date',
            field=models.DateField(verbose_name='تاریخ رویداد'),
        ),
        migrations.AlterField(
            model_name='calendarevent',
            name='quantity',
            field=models.FloatField(default=0, verbose_name='مقدار'),
        ),
        migrations.AlterField(
            model_name='calendarevent',
            name='title',
            field=models.CharField(max_length=255, verbose_name='عنوان'),
        ),
        migrations.AlterField(
            model_name='calendarevent',
            name='type',
            field=models.CharField(choices=[('order', 'سفارش تولید'), ('vacation', 'تعطیلات'), ('offday', 'روز تعطیل'), ('maintenance', 'تعمیر و نگهداری')], default='appointment', max_length=50, verbose_name='نوع رویداد'),
        ),
        migrations.AddConstraint(
            model_name='calendarevent',
            constraint=models.CheckConstraint(check=models.Q(('quantity__gte', 0)), name='calendar_event_quantity_positive'),
        ),
    ]
