# Generated by Django 3.2.6 on 2025-10-21 06:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mrp', '0126_auto_20251018_1035'),
    ]

    operations = [
        migrations.CreateModel(
            name='ColorCode',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Shade',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='manufacturingorder',
            name='delivery_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاریخ تحویل'),
        ),
        migrations.AddField(
            model_name='manufacturingorder',
            name='hb_type',
            field=models.CharField(blank=True, choices=[('HS', 'HS'), ('HB', 'HB')], max_length=2, null=True, verbose_name='هایبالک/رگولار'),
        ),
        migrations.AddField(
            model_name='manufacturingorder',
            name='color_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='mrp.colorcode', verbose_name='کد رنگ'),
        ),
        migrations.AddField(
            model_name='manufacturingorder',
            name='grade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='mrp.grade', verbose_name='نمره'),
        ),
        migrations.AddField(
            model_name='manufacturingorder',
            name='shade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='mrp.shade', verbose_name='شید/رنگ'),
        ),
    ]
