# Generated by Django 3.2.6 on 2025-08-10 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mrp', '0126_dailyproduction_operators_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyproduction',
            name='speed',
            field=models.FloatField(default=0),
        ),
    ]
