# Generated by Django 3.2.6 on 2025-08-10 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mrp', '0127_alter_dailyproduction_speed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entryform',
            name='la',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='entryform',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='entryform',
            name='tool',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
