# Generated by Django 3.2.6 on 2025-10-21 09:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mrp', '0127_auto_20251021_1019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manufacturingorder',
            name='product_to_manufacture',
            field=models.ForeignKey(blank=True, limit_choices_to={'product_type': 'finished'}, null=True, on_delete=django.db.models.deletion.CASCADE, to='mrp.product'),
        ),
    ]
