# Generated by Django 3.2.6 on 2025-10-21 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mrp', '0128_alter_manufacturingorder_product_to_manufacture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manufacturingorder',
            name='bom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mrp.billofmaterials'),
        ),
    ]
