# Generated by Django 3.2.6 on 2025-08-10 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mrp', '0128_auto_20250810_1539'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyproduction',
            name='moshakhase',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dailyproduction_moshakhase', to='mrp.entryform'),
        ),
    ]
