# Generated by Django 3.2.6 on 2025-08-12 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mrp', '0129_dailyproduction_moshakhase'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyproduction',
            name='wastage_value',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
