# Generated by Django 3.2.6 on 2025-10-21 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mrp', '0129_alter_manufacturingorder_bom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manufacturingorder',
            name='scheduled_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
