# Generated by Django 3.2.6 on 2025-08-15 06:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mrp', '0130_dailyproduction_wastage_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='assetCategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assetcategory_main', to='mrp.assetcategory', verbose_name='دسته بندی'),
        ),
    ]
