# Generated by Django 3.2.6 on 2025-08-16 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mrp', '0131_alter_asset_assetcategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reportName', models.CharField(blank=True, max_length=100, null=True, verbose_name='نام گزارش')),
                ('reportCategory', models.IntegerField(blank=True, choices=[(1, 'دستور کار فعال'), (2, 'دستور کار غیر فعال'), (3, 'کنترل انبار'), (4, 'دارایی'), (5, 'کاربران'), (6, 'اندازه گیری کسب و کار'), (7, 'شخصی سازی شده'), (8, 'پیش بینی'), (9, 'نگهداری زمانبندی شده')], null=True, verbose_name='نوع گزارش')),
                ('reportClassName', models.CharField(blank=True, max_length=100, null=True, verbose_name='نام کلاس')),
                ('reportDetails', models.TextField(blank=True, null=True, verbose_name='شرح')),
                ('reportTemplate', models.CharField(blank=True, max_length=100, null=True, verbose_name='نام قالب')),
                ('reportFav', models.BooleanField(default=True, verbose_name='گزارش مورد علاقه')),
                ('timeStamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'reports',
                'ordering': ('reportName',),
            },
        ),
    ]
